### ISSUE TITLE
Sample questions from my interview

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/interview-prep#1]
From me and @mantagen 

How has your project experience aligned to what we're trying to achieve?

What's your experience with agile methodologies?

What do you expect from me as a scrum master?

How do you tend to organise tasks?

How have you gone from recording user stories to breaking them out into tasks to build?

What area of development are you most interested in? (planning, frontend, backend)

**Comment by iteles** [comment]
Awesome, thanks for these! Happy for you to PR these into the readme under a 'Sample Questions' heading so you can get a little credit for them 😊

So no technical questions at all?

**Comment by hdrdavies** [comment]
No actually... 

Will submit a PR!

**Comment by notenociz** [comment]
👍 these are great example questions

**Comment by hdrdavies** [comment]
do I have write access @iteles ? Getting a 403 error...

**Comment by nelsonic** [comment]
@hdrdavies I'm on it. one minute. :hourglass:

**Comment by hdrdavies** [comment]
already done @nelsonic 
:+1:
